from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_vote_booth(object):
    def setupUi(self, vote_booth):
        vote_booth.setObjectName("vote_booth")
        vote_booth.resize(500, 500)
        vote_booth.setMinimumSize(QtCore.QSize(500, 500))
        vote_booth.setMaximumSize(QtCore.QSize(500, 500))
        self.centralwidget = QtWidgets.QWidget(parent=vote_booth)
        self.centralwidget.setObjectName("centralwidget")
        self.label_voting_booth = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_voting_booth.setGeometry(QtCore.QRect(12, 0, 111, 31))
        self.label_voting_booth.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_voting_booth.setObjectName("label_voting_booth")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 140, 91, 16))
        self.label_3.setObjectName("label_3")
        self.label_line_1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_line_1.setGeometry(QtCore.QRect(30, 150, 91, 16))
        self.label_line_1.setObjectName("label_line_1")
        self.label_cand_1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_cand_1.setGeometry(QtCore.QRect(40, 190, 81, 16))
        self.label_cand_1.setObjectName("label_cand_1")
        self.label_cand_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_cand_2.setGeometry(QtCore.QRect(40, 220, 81, 16))
        self.label_cand_2.setObjectName("label_cand_2")
        self.button_cand_2 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.button_cand_2.setGeometry(QtCore.QRect(121, 217, 16, 20))
        self.button_cand_2.setText("")
        self.button_cand_2.setObjectName("button_cand_2")
        self.button_cand_2.setCheckable(True)
        self.button_cand_1 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.button_cand_1.setGeometry(QtCore.QRect(121, 188, 16, 20))
        self.button_cand_1.setText("")
        self.button_cand_1.setObjectName("button_cand_1")
        self.button_cand_1.setCheckable(True)
        self.label_cand_info = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_cand_info.setGeometry(QtCore.QRect(230, 140, 151, 16))
        self.label_cand_info.setObjectName("label_cand_info")
        self.label_line_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_line_2.setGeometry(QtCore.QRect(230, 150, 171, 16))
        self.label_line_2.setObjectName("label_line_2")
        self.label_cand_info_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_cand_info_text.setGeometry(QtCore.QRect(240, 190, 201, 32))
        self.label_cand_info_text.setObjectName("label_cand_info_text")
        self.label_line_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_line_3.setGeometry(QtCore.QRect(30, 333, 101, 16))
        self.label_line_3.setObjectName("label_line_3")
        self.label_curr_tally = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_curr_tally.setGeometry(QtCore.QRect(30, 323, 91, 16))
        self.label_curr_tally.setObjectName("label_curr_tally")
        self.label_cand_1_tally = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_cand_1_tally.setGeometry(QtCore.QRect(40, 363, 81, 16))
        self.label_cand_1_tally.setObjectName("label_cand_1_tally")
        self.label_cand_2_tally = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_cand_2_tally.setGeometry(QtCore.QRect(40, 393, 81, 16))
        self.label_cand_2_tally.setObjectName("label_cand_2_tally")
        self.progressBar_cand_1 = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progressBar_cand_1.setGeometry(QtCore.QRect(130, 361, 118, 23))
        self.progressBar_cand_1.setProperty("value", 45)
        self.progressBar_cand_1.setObjectName("progressBar_cand_1")
        self.progressBar_cand_2 = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progressBar_cand_2.setGeometry(QtCore.QRect(130, 390, 118, 23))
        self.progressBar_cand_2.setProperty("value", 73)
        self.progressBar_cand_2.setInvertedAppearance(False)
        self.progressBar_cand_2.setObjectName("progressBar_cand_2")
        self.label_cand_1_bar_num = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_cand_1_bar_num.setGeometry(QtCore.QRect(260, 363, 60, 16))
        self.label_cand_1_bar_num.setObjectName("label_cand_1_bar_num")
        self.label_cand_2_bar_num = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_cand_2_bar_num.setGeometry(QtCore.QRect(260, 393, 60, 16))
        self.label_cand_2_bar_num.setObjectName("label_cand_2_bar_num")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 363, 121, 16))
        self.label.setObjectName("label")
        self.button_vote_submit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_vote_submit.setGeometry(QtCore.QRect(30, 250, 113, 32))
        self.button_vote_submit.setObjectName("button_vote_submit")
        self.label_line_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_line_4.setGeometry(QtCore.QRect(30, 50, 91, 16))
        self.label_line_4.setObjectName("label_line_4")
        self.label_register = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_register.setGeometry(QtCore.QRect(30, 40, 91, 16))
        self.label_register.setObjectName("label_register")
        self.input_id = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.input_id.setGeometry(QtCore.QRect(90, 78, 113, 21))
        self.input_id.setObjectName("input_id")
        self.label_my_id = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_my_id.setGeometry(QtCore.QRect(40, 80, 60, 16))
        self.label_my_id.setObjectName("label_my_id")
        self.button_validate_id = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_validate_id.setGeometry(QtCore.QRect(205, 73, 81, 32))
        self.button_validate_id.setObjectName("button_validate_id")
        self.label_error_message = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_error_message.setGeometry(QtCore.QRect(290, 80, 171, 16))
        self.label_error_message.setObjectName("label_error_message")
        self.button_vote_again = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_vote_again.setGeometry(QtCore.QRect(289, 384, 141, 32))
        self.button_vote_again.setObjectName("button_vote_again")
        vote_booth.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=vote_booth)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 33))
        self.menubar.setObjectName("menubar")
        vote_booth.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=vote_booth)
        self.statusbar.setObjectName("statusbar")
        vote_booth.setStatusBar(self.statusbar)

        self.retranslateUi(vote_booth)
        QtCore.QMetaObject.connectSlotsByName(vote_booth)

    def retranslateUi(self, vote_booth):
        _translate = QtCore.QCoreApplication.translate
        vote_booth.setWindowTitle(_translate("vote_booth", "MainWindow"))
        self.label_voting_booth.setText(_translate("vote_booth", "Voting Booth"))
        self.label_3.setText(_translate("vote_booth", "Candidates:"))
        self.label_line_1.setText(_translate("vote_booth", "____________"))
        self.label_cand_1.setText(_translate("vote_booth", "candidate_1"))
        self.label_cand_2.setText(_translate("vote_booth", "candidate_2"))
        self.label_cand_info.setText(_translate("vote_booth", "Candidate Information:"))
        self.label_line_2.setText(_translate("vote_booth", "_____________________"))
        self.label_cand_info_text.setText(_translate("vote_booth", "candidate_info_text_placeholder"))
        self.label_line_3.setText(_translate("vote_booth", "_____________"))
        self.label_curr_tally.setText(_translate("vote_booth", "Current Tally:"))
        self.label_cand_1_tally.setText(_translate("vote_booth", "candidate_1"))
        self.label_cand_2_tally.setText(_translate("vote_booth", "candidate_2"))
        self.label_cand_1_bar_num.setText(_translate("vote_booth", "45"))
        self.label_cand_2_bar_num.setText(_translate("vote_booth", "73"))
        self.label.setText(_translate("vote_booth", "*100 needed to win"))
        self.button_vote_submit.setText(_translate("vote_booth", "Vote!"))
        self.label_line_4.setText(_translate("vote_booth", "____________"))
        self.label_register.setText(_translate("vote_booth", "Sign In:"))
        self.label_my_id.setText(_translate("vote_booth", "My ID:"))
        self.button_validate_id.setText(_translate("vote_booth", "Validate"))
        self.label_error_message.setText(_translate("vote_booth", "error_message_placeholder"))
        self.button_vote_again.setText(_translate("vote_booth", "Cast Another Vote"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    vote_booth = QtWidgets.QMainWindow()
    ui = Ui_vote_booth()
    ui.setupUi(vote_booth)
    vote_booth.show()
    sys.exit(app.exec())
